main: main.c astar.h astar.c MapUtils.h MapUtils.c visited_list.h visited_list.c priority_list.h priority_list.c list.h list.c
	clang -fopenmp -Wall -g main.c astar.c MapUtils.c visited_list.c priority_list.c list.c -o main
